FROM python:3.12-slim

ENV PORT=5001

WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install mlflow PyMySQL

VOLUME /app

CMD ["sh", "-c", "mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./model_bank --host 0.0.0.0 --port ${PORT}"]