services:
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyter_lab
    image: jenniferp-cs611:assn2
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--notebook-dir=/app", "--ServerApp.token=''", "--ServerApp.disable_check_xsrf=True"]

  airflow-init:
    build: 
      context: .
      dockerfile: Dockerfile.airflow
    image: jenniferp-cs611-airflow:assn2
    container_name: airflow_init
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=PAqBeGJLJTYFzVkOGHWIYXdLO7XdXz5yTdxAGJe9ezM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./utils:/opt/airflow/utils
      - ./datamart:/app/datamart
      - ./model_bank:/app/model_bank
    entrypoint: >
      /bin/bash -c "airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true"

  airflow-webserver:
    image: jenniferp-cs611-airflow:assn2
    container_name: airflow_webserver
    user: root
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=PAqBeGJLJTYFzVkOGHWIYXdLO7XdXz5yTdxAGJe9ezM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./utils:/opt/airflow/utils
      - ./datamart:/app/datamart
      - ./model_bank:/app/model_bank
    ports:
      - "8080:8080"
    command: >
      bash -c "
        chown -R airflow: /opt/airflow /app/datamart /app/model_bank &&
        chmod -R 755 /app/datamart /app/model_bank &&
        exec su -s /bin/bash airflow -c 'airflow webserver'
      "

  airflow-scheduler:
    image: jenniferp-cs611-airflow:assn2
    container_name: airflow_scheduler
    user: root
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=PAqBeGJLJTYFzVkOGHWIYXdLO7XdXz5yTdxAGJe9ezM=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./utils:/opt/airflow/utils
      - ./datamart:/app/datamart
      - ./model_bank:/app/model_bank
    command: >
      bash -c "
        chown -R airflow: /opt/airflow /app/datamart /app/model_bank &&
        chmod -R 755 /app/datamart /app/model_bank &&
        exec su -s /bin/bash airflow -c 'airflow scheduler'
      "

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    image: jenniferp-cs611-mlflow:assn2
    volumes:
    - .:/app
    ports:
      - "5001:5001"
    

volumes:
  airflow_data:
